## This script defines two functions. makeCacheMatrix() is used to 
## generate a "special" matrix for which the inverse can be readily cached
## and cacheSolve() either computes the inverse of the "special" matrix
## or retrieves the result from the cache if it was previously computed.

## In combination these two functions overcome the need to repeatedly make 
## the time consuming calculation of matrix inverse.

## This function generates a "special" matrix for which the inverse can be cahced
makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        
        get <- function() x
        setInv <- function(inverse) inv <<- inverse
        getInv <- function() inv
        list(set = set, get = get, setInv = setInv, getInv = getInv)
}


## This function either computes the matrix inverse of a matrix generated by
## makeCacheMatrix() or returns an already chached value of the inverse
cacheSolve <- function(x, ...) {
        inv <- x$getInv()
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        inv <- solve(data, ...)
        x$setInv(inv)
        ## Return a matrix that is the inverse of 'x'
        inv     
}
